modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="haegrilontest"
version="1.0.0"
displayName="HaegrilonTest"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Nicodemus, MCreator"
description='''
Medieval decorative items in Excalibur style.
'''

[[dependencies.haegrilontest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




